name: Auto Send Mail and Update OneDrive

on:
  workflow_dispatch:  # hoáº·c dÃ¹ng `schedule` Ä‘á»ƒ Ä‘á»‹nh ká»³ cháº¡y
    # schedule:
    #   - cron: '0 8 * * *'  # cháº¡y má»—i 8h sÃ¡ng UTC

jobs:
  send-mail:
    runs-on: ubuntu-latest

    env:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      TENANT_ID: ${{ secrets.TENANT_ID }}
      USER_EMAIL: ${{ secrets.USER_EMAIL }}

    steps:
      - name: ğŸ”„ Checkout source
        uses: actions/checkout@v3

      - name: ğŸ Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: ğŸ“¦ Install dependencies
        run: pip install -r requirements.txt

      - name: âš™ï¸ Setup Rclone
        uses: animenosekai/setup-rclone@v1.0.0
        with:
          rclone_config: ${{ secrets.RCLONE_CONF }}

      - name: ğŸš€ Run script
        run: python main.py
