name: Auto Send Mail and Update OneDrive

on:
  workflow_dispatch:

jobs:
  send-mail:
    runs-on: ubuntu-latest

    env:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      TENANT_ID: ${{ secrets.TENANT_ID }}
      USER_EMAIL: ${{ secrets.USER_EMAIL }}

    steps:
      - name: ðŸ”„ Checkout source
        uses: actions/checkout@v3

      - name: ðŸ Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: ðŸ“¦ Install dependencies
        run: pip install -r requirements.txt

      - name: ðŸ“¥ Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: ðŸ› ï¸ Setup rclone config
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONF }}" > ~/.config/rclone/rclone.conf

      - name: ðŸš€ Run script
        run: python PingE5_App.py
